projects:
  inverteclientv3:
    schemaPath: src/graphql/schema.json
    includes:
      - amplify/backend/gql/*
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: amplify/backend/gql
extensions:
  amplify:
    version: 3
